services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'file:./dev.db'
      JWT_SECRET: 'suaChaveSecretaAqui'
      JWT_EXPIRES_IN: '1d'
    volumes:
      - sqlite_data:/usr/src/app/prisma

volumes:
  sqlite_data: